FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

RUN apt-get update --fix-missing
RUN apt-get install -y --no-install-recommends 
RUN apt-get install curl -y
RUN apt-get install python3 python3-pip -y
RUN apt-get install git -y

RUN pip3 install mxnet-cu101mkl 
RUN pip3 install ujson
RUN pip3 install -U setuptools
ENV LANG C.UTF-8
ADD . /gluonts

RUN pip3 install /gluonts[shell]

ENTRYPOINT ["python3", "-m", "gluonts.shell"]
